language: bash

services:
  - docker

env:
  global:
    - REPO=zabolotny/mariadb

  matrix:
    - VERSION=10.3.12 TAGS=10.3.12,10.3,10,latest
    - VERSION=10.2.21 TAGS=10.2.21,10.2
    - VERSION=10.1.37 TAGS=10.1.37,10.1
    - VERSION=10.0.37 TAGS=10.0.37,10.0
    - VERSION=5.5.62 TAGS=5.5.62,5.5,5

install:
  - cd ${VERSION%.*}
  - make

after_success:
  - . "${TRAVIS_BUILD_DIR}/release.sh"

after_failure:
  - make logs
